import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer/page";
import Home from "./page";
import Login from "@/components/login";
import Checkout from "@/app/checkout/page";
import CartPage from "@/app/cartpage/page";
import ProductListPage from "@/app/productlist/page";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} px-4 sm:px-6 lg:px-20`}>
        <Navbar/>
        <main>{children}</main>
        {/* <ProductDetail/> */}
        {/* <ProductListPage/> */}
        {/* <Home/> */}
       
        {/* <CartPage/> */}
        {/* <Login/> */}
        {/* <Checkout/> */}
         <Footer/>
        
      </body>
    </html>
  );
}
